sudo: required

language: java

services:
  - docker

install:
  - git clone https://github.com/Aidbox/devbox.git
  - mv .env devbox/.env
  - mv test devbox/test
  - cd devbox
  - wget https://github.com/Aidbox/stresty/releases/download/0.0.9/stresty.jar
  - docker-compose up -d

before_script:
  - curl http://localhost:8888/

script:
  - AIDBOX_URL=http://localhost:8888/ AIDBOX_AUTH_TYPE=Basic AIDBOX_CLIENT_ID=root AIDBOX_CLIENT_SECRET=secret java -jar stresty.jar test/*.yaml

after_script:
  - docker-compose stop
