sudo: required

language: java

services:
  - docker

env:
  - AIDBOX_LICENSE_ID=a556ac913e89449 AIDBOX_LICENSE_KEY=fb5525d7e8254439acd62b3faae91be9

install:
  - git clone https://github.com/Aidbox/devbox.git
  - mv .env devbox/.env
  - mv test devbox/test
  - cd devbox
  - sed -i AIDBOX_LICENSE_KEY .env
  - sed -i AIDBOX_LICENSE_ID .env
  - wget https://github.com/Aidbox/stresty/releases/download/0.0.11/stresty.jar
  - docker-compose up -d

before_script:
  - while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8888/health)" != "200" ]]; do sleep 5; done

script:
  - AIDBOX_URL=http://localhost:8888/ AIDBOX_AUTH_TYPE=Basic AIDBOX_CLIENT_ID=root AIDBOX_CLIENT_SECRET=secret java -jar stresty.jar test/*.yaml

after_script:
  - docker-compose stop
